### ISSUE TITLE
Add CSS only when needed

### ISSUE THREAD

**Issue by damiencarbery** [miya0001/oembed-gist#17]
The wp_head() function adds CSS for every page.
I suggest that the CSS is added to the footer and only when needed.

I think that the solution is to add something like the following to the end of the shortcode() function, just before the 'return sprintf' line:

add_action( 'wp_footer', array( $this, 'wp_head' ) );

I would also like to be able to disable the function - I would instead add the CSS to my own stylesheet.
I think that a static variable is required.

I will try to create a pull request to achieve both of these.

**Comment by miya0001** [comment]
Please see:
https://github.com/miya0001/oembed-gist/pull/19
