### ISSUE TITLE
Allow disabling of injected CSS

### ISSUE THREAD

**Issue by damiencarbery** [miya0001/oembed-gist#18]
This is related to my request in issue #17  to allow disabling the wp_head() function.

I would like to disable the wp_head() function and put the CSS into my stylesheet file.
I suggest using apply_filters().

**Comment by damiencarbery** [comment]
I don't know how this was closed. I am quite new to github.

**Comment by miya0001** [comment]
If you want to remove them you can do it by following code.

```
add_action( 'plugin_loaded', function() {
    global $oe_gist;
    remove_action( 'wp_head', array( $oe_gist, 'wp_head' ) );
}, 11 );
```

**Comment by damiencarbery** [comment]
There is tiny typo in that code - change the hook to 'plugins_loaded'. It works. Thank you.
