### ISSUE TITLE
Gists after the footer?

### ISSUE THREAD

**Issue by brainstorm** [miya0001/oembed-gist#2]
I'm not sure why, but your plugin places my gists after the footer in my blog instead of inline where they are defined:

http://blogs.nopcode.org/brainstorm/2014/03/04/opensource-dashboard/

i.e, in between the lines:

```
The only viable option left today is scraping it:
```

and

```
If one wants to keep track of AWS expenses on ES, some specific
```

There should be a gist, but it's placed that the very end after the footer :-?

**Comment by futtta** [comment]
I've [fixed this on AO's end](https://github.com/futtta/autoptimize/commit/725d7fc3b7adfb46e85150126b6b0970cc671ae0), forcefully excluding gists from optimization. This will be in the next official release on wordpress.org.
