### ISSUE TITLE
WordPress 5

### ISSUE THREAD

**Issue by ijoschek** [miya0001/oembed-gist#27]
Hi,

There seems to be an issue with the new WordPress Update (Version 5)

**Comment by mrechung** [comment]
+1 - not working on wordpress 5

**Comment by GSoster** [comment]
I can't use it with wordpress 5 too

**Comment by GSoster** [comment]
Ops, just discovered that the name of my gists cannot have camelCase. It works ok with my Wordpress 5.0.3

**Comment by ijoschek** [comment]
It works now, the only thing is, it does not show in the editor. Should I close it?

**Comment by saeedesmaili** [comment]
How can we use this in new posts in Wordpress 5, while there is no option in the editor?

**Comment by miya0001** [comment]
Oh! Sorry for late reply. I didn't see...  :)
Are there any problem for now?

**Comment by saeedesmaili** [comment]
Have you tried the plugin in Wordpress 5? I'm using it with some tricks, but it doesn't have any button in the editor to insert a new gist.

**Comment by miya0001** [comment]
Oh I see. Please wait couple of days.
Thanks people :)

**Comment by CedricL46** [comment]
@saeedesmaili You can still use it with WordPress 5. In Gutenberg you just need to create a classic editor block and paste it in this block and not another. Works well for me.

**Comment by CedricL46** [comment]
@miya0001 This is not a bug and work fine if you simply use the "Classic editor" Gutenberg block to paste your link! :)
