### ISSUE TITLE
Wordpress 4.1 2015 theme compatibility

### ISSUE THREAD

**Issue by gusrub** [miya0001/oembed-gist#4]
Hello, I wonder if this plugin is compatible with the _2015_ or _Twelve Fifteen_ theme default wordpress theme that is shipped in 4.1.

This is how it looks, no modifications to the theme whatsoever:

![screenshot from 2015-01-11 19 55 38](https://cloud.githubusercontent.com/assets/2460982/5698925/d5ba972a-99ce-11e4-9ac6-0a5dfadf3a6d.png)

I think it's something to do with the default styling of the theme for `TD` table elements, maybe overriding the default theme style would help? AFAIK this code is just embeded version of github own's html generated code right?

**Comment by miya0001** [comment]
Hi @gusrub,

Thanks! I've fixed.

**Comment by gusrub** [comment]
Amazing! Should I just download the latest from master and replace? I'm guessing the update won't be on the wordpress plugin manager yet would it?

**Comment by gusrub** [comment]
Forget it, wrote too quick, I see the update on wordpress, thanks again!
