### ISSUE TITLE
does not show on below link

### ISSUE THREAD

**Issue by changsijay** [miya0001/oembed-gist#7]
after I changed the file name to `HelloApplication.java`
it doesn't work, maybe cause case insensitive issue or something?

https://gist.github.com/changsijay/ee624d079cd4d0bd5c2f#file-helloapplication-java

**Comment by miya0001** [comment]
> it doesn't work, maybe cause case insensitive issue or something?

Yes, maybe It's a bug of the Gist. :smile: 

URL should be like following.
https://gist.github.com/changsijay/ee624d079cd4d0bd5c2f#file-HelloApplication-java

**Comment by changsijay** [comment]
got it, it works as your method, thanks a lot :+1:
